config/routes.rb
Rails.application.routes.draw do
  root 'linkedin#index'
  resources :linkedin, only: :index
  resources :github, only: :index

end

app/models/github.rb
class Github < ActiveRecord::Base
  require 'csv'
#https://github.com/b4thestorm?tab=repositories
#scrape Repos information from Github 
MAP = ['iHelp', 'Connected', 'Adjust', 'Group',  'Gridstack', 'My Blog', 'Music API Client', 'Reservester', 'Practice', 'Odin' , 'PIZZA', 'BlackJack', 'Scope', 'testProject' ]

def import_repo_info
  filename = File.join(Rails.root, "github.csv") 
  read_repo = CSV.read(filename, :encoding => 'ISO-8859-1', :headers => true, :header_converters => :symbol)
  set_object = read_repo.each {|col| Github.create(url: col[:url], description: col[:description])} 
end



end

app/models/linkedin.rb
class Linkedin < ActiveRecord::Base
require 'csv'


#this model is supposed to represent my resume as it appears on linkedin

def import_resume
    filename = File.join(Rails.root, "arnold.csv")
    read_file = CSV.read(filename, :encoding => 'ISO-8859-1', :headers => true, :header_converters => :symbol)  
    set_object = read_file.each {|col| Linkedin.create(name: col[:name],title: col[:title],experience: col[:experience],summary: col[:summary], education: col[:education], skills: col[:skills] )}                                  
end

# ["id", "name", "title", "experience", "summary", "education", "skills", "created_at", "updated_at"]


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/github_controller.rb
class GithubController < ApplicationController

def index 
   @list = Github.all
end 

end

app/controllers/linkedin_controller.rb
class LinkedinController < ApplicationController

def index 
  @profile  = Linkedin.first
end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/github_helper.rb
module GithubHelper



end 

app/helpers/linkedin_helper.rb
module LinkedinHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HeyArnold</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
        <div class="col-md-12">
        <div class="header">
          <h1>Arnold Sanders.</h1>
        </div>
        <div class="tagline">
          <h2> Biology grad. 
            Rails developer. </br>
           Problem solver, with a scientific mind.
           Curious of everything. Dreamer!</h2>
        </div>
        </div>
        <hr>
        <div class="container">
        <center>
        <ul>
          <li><%= link_to 'LinkedIn', linkedin_index_path %></li>
          <li><%= link_to 'GitHub', github_index_path %></li>
          <li>Blog</li>
        </ul> 
      </center>


<%= yield %>
              
        </div>

</body>
</html>